# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dbb69645a5b24f122c2893492bd92a6b7670f853e739ed7c6ead5474fb480906c098209921c09916e8841907f7f6098a37a26995a233a625962b3de68d02352
  dropbox_key: 9ujd9ao4qn65qyg
  dropbox_secret: yqv0lk709x8oqo5
  onedrive_key: 0000000044179846
  onedrive_secret: yslsMJbSl1zrynghwTvl5JgUdWoh2sS3

test:
  secret_key_base: 349bce7faf21753b2a4a0ff8d753e3a406c7559f590791730e03a98b90ad771284558341fcf4c7d48e05dbde6ebba38577efcfa8acfc7e1aeb784945d0435921
  dropbox_key: 9ujd9ao4qn65qyg
  dropbox_secret: yqv0lk709x8oqo5
  onedrive_key: 0000000044179846
  onedrive_secret: yslsMJbSl1zrynghwTvl5JgUdWoh2sS3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  dropbox_key: <%= ENV["DROPBOX_KEY"] %>
  dropbox_secret: <%= ENV["DROPBOX_SECRET"] %>
  onedrive_key: <%= ENV["ONEDRIVE_KEY"] %>
  onedrive_secret: <%= ENV["ONEDRIVE_SECRET"] %>
